# Generated by Django 5.1 on 2024-08-18 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with +260 and be 14 characters long.', regex='^\\+260\\d{10}$')]),
        ),
    ]
