# Generated by Django 5.1 on 2024-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_driver",
            field=models.BooleanField(default=False),
        ),
    ]
