# Generated by Django 5.1 on 2024-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/thumbnails/"
            ),
        ),
    ]
