# Generated by Django 5.1 on 2024-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="delivery_time",
            field=models.PositiveIntegerField(),
        ),
    ]
