# Generated by Django 5.1 on 2024-08-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0003_balance_last_cashout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance",
            old_name="last_cashout",
            new_name="last_interest_calculation",
        ),
    ]
