# Generated by Django 5.1 on 2024-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0003_alter_product_delivery_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="product_default.png",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
