# Generated by Django 5.1 on 2024-09-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0005_alter_balance_request_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashoutrequest",
            name="is_approved",
        ),
    ]
