# Generated by Django 5.1 on 2024-08-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0005_rename_last_interest_calculation_balance_last_cashout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="last_cashout",
        ),
    ]
