# Generated by Django 5.1 on 2024-08-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0006_remove_balance_last_cashout"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="last_cashout",
            field=models.DateField(blank=True, null=True),
        ),
    ]
