# Generated by Django 5.1 on 2024-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0006_remove_cashoutrequest_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashoutrequest",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
