# Generated by Django 5.1 on 2024-09-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0007_cashoutrequest_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
