# Generated by Django 5.1 on 2024-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0008_cashoutrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="request_limit",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
