# Generated by Django 5.1 on 2024-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0008_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("books", "Books"),
                    ("home", "Home & Garden"),
                    ("toys", "Toys & Games"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
    ]
