# Generated by Django 5.1 on 2024-08-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0009_balance_request_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashoutrequest",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
