# Generated by Django 5.1 on 2024-10-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0009_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
