# Generated by Django 5.1 on 2024-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0010_cashoutrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashrequest",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
