# Generated by Django 5.1 on 2024-08-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0012_product_cart_order_invoice_orderitem_cartitem_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
