# Generated by Django 5.1 on 2024-10-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0012_product_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("groceries", "Groceries"),
                    ("hardware", "Hardware"),
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("furniture", "Furniture"),
                    ("automotive", "Automotive"),
                    ("beauty_health", "Beauty & Health"),
                    ("toys", "Toys"),
                    ("sports", "Sports & Outdoors"),
                    ("books", "Books"),
                    ("home_appliances", "Home Appliances"),
                    ("stationery", "Stationery"),
                    ("pharmacy", "Pharmacy"),
                    ("jewelry", "Jewelry & Accessories"),
                    ("footwear", "Footwear"),
                    ("gardening", "Gardening & Outdoor"),
                    ("baby_products", "Baby Products"),
                    ("pet_supplies", "Pet Supplies"),
                    ("music_instruments", "Musical Instruments"),
                    ("office_supplies", "Office Supplies"),
                    ("gaming", "Gaming"),
                    ("kitchenware", "Kitchenware"),
                    ("building_materials", "Building Materials"),
                    ("tools", "Tools & Equipment"),
                    ("computer_accessories", "Computer & Accessories"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_term", models.CharField(max_length=255)),
                ("search_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
