# Generated by Django 5.1 on 2024-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0013_alter_product_category_searchlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Synonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255, unique=True)),
                ("main_term", models.CharField(max_length=255)),
            ],
        ),
    ]
