# Generated by Django 5.1 on 2024-08-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0013_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
