# Generated by Django 5.1 on 2024-08-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0014_alter_order_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
