# Generated by Django 5.1 on 2024-10-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0014_synonym"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchlog",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="referrer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="results_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="searchlog",
            name="search_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
