# Generated by Django 5.1 on 2024-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0015_searchlog_category_searchlog_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchlog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="max_price",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="min_price",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="referrer",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="results_count",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="user_agent",
        ),
        migrations.AlterField(
            model_name="searchlog",
            name="search_date",
            field=models.DateTimeField(),
        ),
    ]
