# Generated by Django 5.1 on 2024-10-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0017_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="business_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
