# Generated by Django 5.1 on 2024-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0018_order_business_location_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
