# Generated by Django 5.1 on 2024-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0019_product_stock_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
