# Generated by Django 5.1 on 2024-11-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0022_quizquestion_quizscore_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizscore",
            name="username",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
