# Generated by Django 5.1 on 2024-11-16 22:43

import mma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0024_chatroom_chatuser_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(
                default=mma.models.generate_random_name, max_length=255
            ),
        ),
        migrations.DeleteModel(
            name="ChatUser",
        ),
    ]
