# Generated by Django 5.1 on 2024-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0025_remove_message_user_message_username_delete_chatuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthdayWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=100)),
                ("recipient_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
